import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// auth.ts reads DATA_DIR / STUDIO_PASSWORD at import time, so each test imports a fresh copy.
async function loadAuth(env: Record<string, string | undefined>) {
  vi.resetModules();
  for (const [k, v] of Object.entries(env)) {
    if (v === undefined) delete process.env[k];
    else process.env[k] = v;
  }
  return import('./auth');
}

let dataDir: string;
const saved = { ...process.env };

beforeEach(() => {
  dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bb-auth-'));
});

afterEach(() => {
  process.env = { ...saved };
  vi.useRealTimers();
  fs.rmSync(dataDir, { recursive: true, force: true });
});

describe('first-visit password setup', () => {
  it('lets the first visitor create a password, then behaves like a normal login', async () => {
    const auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: undefined });
    expect(auth.isClaimed()).toBe(false);
    expect(auth.setupOpen()).toBe(true);

    expect(auth.claimPassword('short')).toBe('too-short');
    expect(auth.claimPassword('my-own-password')).toBe('ok');

    expect(auth.isClaimed()).toBe(true);
    expect(auth.setupOpen()).toBe(false);
    expect(auth.claimPassword('someone-else-123')).toBe('claimed');
    expect(auth.checkPassword('my-own-password')).toBe(true);
    expect(auth.checkPassword('someone-else-123')).toBe(false);

    const stored = fs.readFileSync(path.join(dataDir, 'password.json'), 'utf8');
    expect(stored).not.toContain('my-own-password');
  });

  it('keeps the chosen password across restarts', async () => {
    let auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: undefined });
    auth.claimPassword('my-own-password');
    auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: undefined });
    expect(auth.isClaimed()).toBe(true);
    expect(auth.setupOpen()).toBe(false);
    expect(auth.checkPassword('my-own-password')).toBe(true);
  });

  it('closes setup after the window if nobody claimed the studio', async () => {
    vi.useFakeTimers();
    const auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: undefined });
    vi.advanceTimersByTime(auth.SETUP_WINDOW_MS + 1);
    expect(auth.setupOpen()).toBe(false);
    expect(auth.claimPassword('my-own-password')).toBe('closed');
    expect(auth.checkPassword('my-own-password')).toBe(false);
  });

  it('skips setup when STUDIO_PASSWORD is set, and treats change-me as unset', async () => {
    let auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: 'from-the-env-1' });
    expect(auth.isClaimed()).toBe(true);
    expect(auth.claimPassword('my-own-password')).toBe('claimed');
    expect(auth.checkPassword('from-the-env-1')).toBe(true);

    auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: 'change-me' });
    expect(auth.isClaimed()).toBe(false);
    expect(auth.checkPassword('change-me')).toBe(false);
  });

  it('still accepts a PASSWORD.txt generated by older images', async () => {
    fs.writeFileSync(path.join(dataDir, 'PASSWORD.txt'), 'amber-river-1234\n');
    const auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: undefined });
    expect(auth.isClaimed()).toBe(true);
    expect(auth.checkPassword('amber-river-1234')).toBe(true);
  });
});

describe('agent token', () => {
  it('creates a private token file on first boot and keeps it across restarts', async () => {
    let auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_AGENT_TOKEN: undefined, AGENT_ACCESS: undefined });
    expect(auth.ensureAgentToken()).toBe(true);
    const file = path.join(dataDir, 'agent-token');
    const token = fs.readFileSync(file, 'utf8').trim();
    expect(token).toMatch(/^bbs_[A-Za-z0-9_-]{43}$/);
    expect(fs.statSync(file).mode & 0o777).toBe(0o600);
    expect(auth.checkAgentToken(token)).toBe(true);
    expect(auth.checkAgentToken(token + 'x')).toBe(false);
    expect(auth.checkAgentToken('')).toBe(false);

    auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_AGENT_TOKEN: undefined, AGENT_ACCESS: undefined });
    auth.ensureAgentToken();
    expect(auth.checkAgentToken(token)).toBe(true);
  });

  it('rotation invalidates the old token at once', async () => {
    const auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_AGENT_TOKEN: undefined, AGENT_ACCESS: undefined });
    auth.ensureAgentToken();
    const old = fs.readFileSync(path.join(dataDir, 'agent-token'), 'utf8').trim();
    expect(auth.rotateAgentToken()).toBe('ok');
    const fresh = fs.readFileSync(path.join(dataDir, 'agent-token'), 'utf8').trim();
    expect(fresh).not.toBe(old);
    expect(auth.checkAgentToken(old)).toBe(false);
    expect(auth.checkAgentToken(fresh)).toBe(true);
  });

  it('AGENT_ACCESS=false creates no file and rejects every bearer', async () => {
    const auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_AGENT_TOKEN: 'x'.repeat(40), AGENT_ACCESS: 'false' });
    expect(auth.ensureAgentToken()).toBe(false);
    expect(fs.existsSync(path.join(dataDir, 'agent-token'))).toBe(false);
    expect(auth.checkAgentToken('x'.repeat(40))).toBe(false);
    expect(auth.rotateAgentToken()).toBe('off');
  });

  it('uses STUDIO_AGENT_TOKEN when set, and ignores one too short to be safe', async () => {
    let auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_AGENT_TOKEN: 'k'.repeat(40), AGENT_ACCESS: undefined });
    expect(auth.ensureAgentToken()).toBe(true);
    expect(auth.checkAgentToken('k'.repeat(40))).toBe(true);
    expect(auth.rotateAgentToken()).toBe('env');
    expect(fs.existsSync(path.join(dataDir, 'agent-token'))).toBe(false);

    auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_AGENT_TOKEN: 'short', AGENT_ACCESS: undefined });
    expect(auth.ensureAgentToken()).toBe(false);
    expect(auth.checkAgentToken('short')).toBe(false);
  });
});

describe('public paths', () => {
  it('keeps the API, media and MCP behind auth; signed links check themselves', async () => {
    const auth = await loadAuth({ DATA_DIR: dataDir });
    for (const p of ['/api/system', '/media/a.png', '/mcp', '/mcp/x']) expect(auth.isPublicPath(p)).toBe(false);
    for (const p of ['/', '/projects', '/assets/index.js', '/api/login', '/api/health', '/dl/abc/1/sig/x.mp4']) expect(auth.isPublicPath(p)).toBe(true);
  });
});
