import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// auth.ts reads DATA_DIR / STUDIO_PASSWORD at import time, so each test imports a fresh copy.
async function loadAuth(env: Record<string, string | undefined>) {
  vi.resetModules();
  for (const [k, v] of Object.entries(env)) {
    if (v === undefined) delete process.env[k];
    else process.env[k] = v;
  }
  return import('./auth');
}

let dataDir: string;
const saved = { ...process.env };

beforeEach(() => {
  dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bb-auth-'));
});

afterEach(() => {
  process.env = { ...saved };
  vi.useRealTimers();
  fs.rmSync(dataDir, { recursive: true, force: true });
});

describe('first-visit password setup', () => {
  it('lets the first visitor create a password, then behaves like a normal login', async () => {
    const auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: undefined });
    expect(auth.isClaimed()).toBe(false);
    expect(auth.setupOpen()).toBe(true);

    expect(auth.claimPassword('short')).toBe('too-short');
    expect(auth.claimPassword('my-own-password')).toBe('ok');

    expect(auth.isClaimed()).toBe(true);
    expect(auth.setupOpen()).toBe(false);
    expect(auth.claimPassword('someone-else-123')).toBe('claimed');
    expect(auth.checkPassword('my-own-password')).toBe(true);
    expect(auth.checkPassword('someone-else-123')).toBe(false);

    const stored = fs.readFileSync(path.join(dataDir, 'password.json'), 'utf8');
    expect(stored).not.toContain('my-own-password');
  });

  it('keeps the chosen password across restarts', async () => {
    let auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: undefined });
    auth.claimPassword('my-own-password');
    auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: undefined });
    expect(auth.isClaimed()).toBe(true);
    expect(auth.setupOpen()).toBe(false);
    expect(auth.checkPassword('my-own-password')).toBe(true);
  });

  it('closes setup after the window if nobody claimed the studio', async () => {
    vi.useFakeTimers();
    const auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: undefined });
    vi.advanceTimersByTime(auth.SETUP_WINDOW_MS + 1);
    expect(auth.setupOpen()).toBe(false);
    expect(auth.claimPassword('my-own-password')).toBe('closed');
    expect(auth.checkPassword('my-own-password')).toBe(false);
  });

  it('skips setup when STUDIO_PASSWORD is set, and treats change-me as unset', async () => {
    let auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: 'from-the-env-1' });
    expect(auth.isClaimed()).toBe(true);
    expect(auth.claimPassword('my-own-password')).toBe('claimed');
    expect(auth.checkPassword('from-the-env-1')).toBe(true);

    auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: 'change-me' });
    expect(auth.isClaimed()).toBe(false);
    expect(auth.checkPassword('change-me')).toBe(false);
  });

  it('still accepts a PASSWORD.txt generated by older images', async () => {
    fs.writeFileSync(path.join(dataDir, 'PASSWORD.txt'), 'amber-river-1234\n');
    const auth = await loadAuth({ DATA_DIR: dataDir, STUDIO_PASSWORD: undefined });
    expect(auth.isClaimed()).toBe(true);
    expect(auth.checkPassword('amber-river-1234')).toBe(true);
  });
});
